### ISSUE TITLE
Accidentally installing go-licenses as well

### ISSUE THREAD

**Issue by wolfv** [conda-forge/restic-feedstock#11]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

At least the Windows package also contains the `go-licenses.exe` file (which doubles the size of the package!)

You shoudl depend on `go-licenses` or delete the file after use.

### Installed packages

```shell
None
```

### Environment info

```shell
None
```

**Comment by anjos** [comment]
Righty, thanks for the heads-up.  Totally my bad with the change in the licensing requirements from saga #6

**Comment by anjos** [comment]
Of course, the last patch did not fix this issue...

**Comment by anjos** [comment]
There, this should fix it.  The packages are now back to their original sizes.

**Comment by wolfv** [comment]
Thanks for taking care of this @anjos! :)
